name: test-pipline
run-name: something was commitet
on: [push]
jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
    - name: 🛎 Checkout
      uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          bash run.sh
          echo "Luca"

  print-username:
    runs-on: ubuntu-latest
    steps:
    - name: say-hello
      run: echo  hello world!
      
  prints-secret:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: echo  "$TEST_SECRET"
  
