name: test-pipline
run-name: something was commitet
on: [push]
jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
    - name: 🛎 Checkout
      uses: actions/checkout@v2
  print-username:
    runs-on: ubuntu-latest
    steps:
    - name: say-hello
      run: echo  hello world!
  prints-secret:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: echo  "$TEST_SECRET"
  
