name: test-pipline
run-name: something was commitet
on: [push]
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
    - name: say-hello
      run: echo  hello world!
  prints-secret:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SuperSecret }}
      run: |
         example-command "$SUPER_SECRET"
  
